"""Generate fixtures/tiny.pdf: one page, four lines, one of them a 'Total' row.

Hand-rolled so the fixture needs no PDF library and can be regenerated byte for
byte. Run: python fixtures/make_tiny_pdf.py
"""
import pathlib

stream = (
    b"BT /F1 12 Tf 20 170 Td (Methods) Tj "
    b"0 -20 Td (alpha 2) Tj "
    b"0 -20 Td (beta 3) Tj "
    b"0 -20 Td (Total 5) Tj ET"
)

objects = [
    b"<< /Type /Catalog /Pages 2 0 R >>",
    b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
    b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    b"<< /Length %d >>\nstream\n%s\nendstream" % (len(stream), stream),
    b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
]

out = bytearray(b"%PDF-1.4\n")
offsets = []
for number, body in enumerate(objects, start=1):
    offsets.append(len(out))
    out += b"%d 0 obj\n" % number + body + b"\nendobj\n"

startxref = len(out)
out += b"xref\n0 %d\n" % (len(objects) + 1)
out += b"0000000000 65535 f \n"
for offset in offsets:
    out += b"%010d 00000 n \n" % offset
out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
    len(objects) + 1, startxref,
)

path = pathlib.Path(__file__).parent / "tiny.pdf"
path.write_bytes(bytes(out))
print(f"wrote {path} ({len(out)} bytes)")
